src/Entity/User.php
<?php
// src/App/Entity/User.php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="users")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=32, nullable=false)
     */
    protected $name;

    /** @ORM\Column(type="string", length=255, nullable=true) */
    protected $twitch_id;

    /** @ORM\Column(type="string", length=255, nullable=true) */
    protected $twitch_access_token;


    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return User
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return User
     */
    public function setName(string $name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getTwitchId()
    {
        return $this->twitch_id;
    }

    /**
     * @param mixed $twitch_id
     * @return User
     */
    public function setTwitchId($twitch_id)
    {
        $this->twitch_id = $twitch_id;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getTwitchAccessToken()
    {
        return $this->twitch_access_token;
    }

    /**
     * @param mixed $twitch_access_token
     * @return User
     */
    public function setTwitchAccessToken($twitch_access_token)
    {
        $this->twitch_access_token = $twitch_access_token;
        return $this;
    }




}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use NewTwitchApi\HelixGuzzleClient;
use NewTwitchApi\NewTwitchApi;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        if ($this->getUser())
            return $this->redirectToRoute('view');

        return $this->render('home/index.html.twig');
    }

    /**
     * @Route("/view", name="view")
     */
    public function view(Request $request)
    {
        $channel = $request->query->get('channel');

        if (!$channel)
            return $this->render('home/channel.html.twig');


        $clientId = getenv('TWITCH_ID');
        $options = [
            'client_id' => $clientId,
            'timeout' => 10,
        ];

        $accessToken = $this->getUser()->getTwitchAccessToken();
        $twitchApi = new \TwitchApi\TwitchApi($options);
        $twitchApi->setTimeout(10);

        $user = $twitchApi->getUserByUsername($channel);

        if (!isset($user['users'][0]))
            return $this->render('home/channel.html.twig', ['error' => 'Cannot find a channel for '.$channel]);

//        $id = $user['users'][0]['_id'];
//        $broadcast = $twitchApi->getLiveStreams($id);
//        $topics = [
//            "channel-bits-events-v1.$id",
////            "channel-bits-badge-unlocks.$id",
////            "channel-subscribe-events-v1.$id",
//        ];

        return $this->render('home/app.html.twig', [
            'client_id' => $clientId,
            'channel' => $channel,
            'access_token' => $accessToken,
//            'topics' => implode(',',$topics),
        ]);

    }

    /**
     * Testing Webhooks
     */
    public function view2() {
        $clientId = getenv('TWITCH_ID');
        $clientSecret = getenv('TWITCH_SECRET');
        $accessToken = $this->getUser()->getTwitchAccessToken();

        $helixGuzzleClient = new HelixGuzzleClient($clientId);
        $newTwitchApi = new NewTwitchApi($helixGuzzleClient, $clientId, $clientSecret);

        $channelId = "37402112";

        $newTwitchApi->getWebhooksSubscriptionApi()->subscribeToStream(
            $channelId,
            'bearer-token',
            'http://requestbin.fullcontact.com/12s15qk1',
            1000
        );

        exit;

        try {
            // Make the API call. A ResponseInterface object is returned.
            $response = $newTwitchApi->getUsersApi()->getUserByAccessToken($accessToken);
        } catch (GuzzleException $e) {
            // Handle error appropriately for your application
        }

    }



}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.png') }}"/>

        <title>{% block title %}Twitch - Streamlabs Event Viewer{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
    <div class="container">
        {% block body %}{% endblock %}
    </div>


        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


        <script src="{{ asset('bundles/goswebsocket/js/vendor/autobahn.min.js') }}"></script>
        <script src="{{ asset('bundles/goswebsocket/js/gos_web_socket_client.js') }}"></script>

        {% block javascripts %}
        {% endblock %}
    </body>
</html>

templates/home/app.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="row">
        <div class="col-12 ml-auto mr-auto text-center">
            <br>
            <a class="btn btn-light" href="{{ path('view') }}">Search Again</a>
            <a class="btn btn-light" href="{{ path('fos_user_security_logout') }}">Logout</a>
            <br><br>

            <div id="twitch-embed"></div>
        </div>
    </div>

    <br><br>
    <div class="row">
        <div class="col-8 ml-auto mr-auto">

            <h5>Last 10 Events</h5>
            <div class="ws-output"></div>
        </div>
    </div>

    <br><br><br>


{% endblock %}

{% block javascripts %}
    <script src="https://embed.twitch.tv/embed/v1.js"></script>
    <script src="//gitcdn.xyz/repo/tmijs/cdn/master/latest/1.x/tmi.js"></script>

    <script>

        // https://docs.tmijs.org/v1.4.2/Commands.html
        const options = {
            options: {
                // debug: true
            },
            connection: {
                reconnect: true,
                secure: true,
            },
            identity: {
                username: "LeekaTVBot",
                password: "oauth:{{ app.user.twitchAccessToken }}"
            },
            channels: ['{{ channel }}']
        };

        const client = new tmi.client(options);

        client.on("cheer", (channel, userstate, message) => {

            var msg = userstate.username + " Cheered for " + userstate.bits + " bits";
            events.unshift(msg);
            update();
        });

        client.on("subscription", (channel, username, method, message, userstate) => {

            var msg = username + " " + method.plan + " Subscription";

            events.unshift(msg);
            update();
        });

        client.on("resub", function (channel, username, months, message) {
            var msg = username + " Subbed for " + months + " Months - "+message;

            events.unshift(msg);
            update();
        });

        client.on("subgift", (channel, username, streakMonths, recipient, methods, userstate) => {

            var msg = username +" gifted " + recipient + "a sub";
            events.unshift(msg);
            update();
        });

        client.connect().then(function(data) {
            console.dir('CONNECTED')
            // data returns [server, port]
        }).catch(function(err) {
            console.dir('NOT CONNECTED');
            console.dir(err);
        });

        var events = [];

        function update() {

            // only show 10 events
            if (events.length > 10)
                events.pop();

            // todo
            $('.ws-output').html('');
            var time = new Date().toLocaleTimeString();

            events.forEach(function(entry) {

                var html = "<div class='card'><div class='card-body'><small>"+time + " | "+entry+"</small></div></div>";
                $('.ws-output').append(html);
            });
        }

        var embed = new Twitch.Embed("twitch-embed", {
            width: 1000,
            height: 480,
            channel: "{{ channel }}",
        });

    </script>

{% endblock %}

templates/home/channel.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <br>
    <div class="row">
        <div class="col-6 ml-auto mr-auto">

            {% if error is defined %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}

            <form method="get" class=e">
                <label for="channel">
                    Twitch User Search:
                </label>
                <input id="channel" type="text" name="channel" class="form-control" required>
                <div class="text-right">
                    <br>
                    <button class="btn btn-success">Search</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="row">
        <div class="col-12 text-center">
            <br><br>
            <h5>StreamerEventViewer Demo App</h5>

            <br><br>
            <a class="btn btn-primary" href="{{ path('hwi_oauth_service_redirect', {service: 'twitch'}) }}">
                Connect with Twitch
            </a>
        </div>
    </div>

{% endblock %}

templates/home/sample.html.twig
<script>

    var clientId = '{{ client_id}}';
    var redirectURI = 'http://dev.sl.com';
    var scope = 'user_read+chat:read';
    var ws;

    // function parseFragment(hash) {
    //     var hashMatch = function(expr) {
    //         var match = hash.match(expr);
    //         return match ? match[1] : null;
    //     };
    //     var state = hashMatch(/state=(\w+)/);
    //     if (sessionStorage.twitchOAuthState == state)
    //         sessionStorage.twitchOAuthToken = hashMatch(/access_token=(\w+)/);
    //     return
    // };

    // function authUrl() {
    //     sessionStorage.twitchOAuthState = nonce(15);
    //     var url = 'https://api.twitch.tv/kraken/oauth2/authorize' +
    //         '?response_type=token' +
    //         '&client_id=' + clientId +
    //         '&redirect_uri=' + redirectURI +
    //         '&state=' + sessionStorage.twitchOAuthState +
    //         '&scope=' + scope;
    //     return url
    // }

    // Source: https://www.thepolyglotdeveloper.com/2015/03/create-a-random-nonce-string-using-javascript/
    function nonce(length) {
        var text = "";
        var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        for (var i = 0; i < length; i++) {
            text += possible.charAt(Math.floor(Math.random() * possible.length));
        }
        return text;
    }

    function heartbeat() {
        message = {
            type: 'PING'
        };
        $('.ws-output').append('SENT: ' + JSON.stringify(message) + '\n');
        ws.send(JSON.stringify(message));
    }

    function listen() {
        message = {
            type: 'LISTEN',
            nonce: nonce(15),
            data: {
                topics: ['{{ topics }}'],
                auth_token: '{{ app.user.twitchAccessToken }}'
            }
        };
        $('.ws-output').append('SENT: ' + JSON.stringify(message) + '\n');
        ws.send(JSON.stringify(message));
    }

    function connect() {
        var heartbeatInterval = 1000 * 60; //ms between PING's
        var reconnectInterval = 1000 * 3; //ms to wait before reconnect
        var heartbeatHandle;

        ws = new WebSocket('wss://pubsub-edge.twitch.tv');

        ws.onopen = function(event) {
            $('.ws-output').append('INFO: Socket Opened\n');
            heartbeat();
            listen();
            heartbeatHandle = setInterval(heartbeat, heartbeatInterval);
        };

        ws.onerror = function(error) {
            $('.ws-output').append('ERR:  ' + JSON.stringify(error) + '\n');
        };

        ws.onmessage = function(event) {
            message = JSON.parse(event.data);
            $('.ws-output').append('RECV: ' + JSON.stringify(message) + '\n');
            if (message.type == 'RECONNECT') {
                $('.ws-output').append('INFO: Reconnecting...\n');
                setTimeout(connect, reconnectInterval);
            }
        };

        ws.onclose = function() {
            $('.ws-output').append('INFO: Socket Closed\n');
            clearInterval(heartbeatHandle);
            $('.ws-output').append('INFO: Reconnecting...\n');
            setTimeout(connect, reconnectInterval);
        };

    }


    $(function() {
            connect();
            $('.socket').show()
            $.ajax({
                url: "https://api.twitch.tv/kraken/user",
                method: "GET",
                headers: {
                    "Client-ID": '{{ client_id}}',
                    "Authorization": "OAuth " + '{{ app.user.twitchAccessToken}}'
                }})
                .done(function(user) {
                });
    });


</script>